#ifndef PROJECTCONFIG_H
#define PROJECTCONFIG_H

//#define LED_MODULE
//#define MATRIX_KEYS_MODULE
#define SINGLE_KEY_MODULE
#define EEPROM_24C02_MODULE
#define DECODER_74HC138_MODULE
//#define SEG_DISPLAY_MODULE
#define SINGLE_LED_DISPALY_74HC595_MODULE
#define ADC_XPT2046_MODULE
#define TIME_DS1302_MODULE
#define INFRARED_MODULE
#define TEMPERATURE_DS18B20_MODULE
#define MOTOR_MODULE

#endif /* PROJECTCONFIG_H */
